Apiproductlist
CraftAcademy/slowfood_api_team_1 pull request #3
Opened 2020-03-03 14:10 UTC by emtalen

As a restaurant API
In order to serve a client with products
I would like to be able to provide an endpoint for a products index

We added a model and controller for products and set the routes to do a GET request and then see all products. Each product has an ID, category, name, description and price.

2020-03-03 15:11 UTC, tochman requested changes

2020-03-03 15:11 UTC, tochman commented on app/models/product.rb
> +  validates_presence_of :category_id, :name, :price
Please remove `category_id`  for now.

2020-03-03 15:11 UTC, tochman commented on config/application.rb
> +      end
Please format your code properly. I can't really read this.

2020-03-03 15:11 UTC, tochman commented on config/routes.rb
>      end
If I ware you, I would remove the `v0` name space now.

2020-03-03 15:11 UTC, tochman commented on db/migrate/20200303132228_create_products.rb
> +      t.bigint :category_id
Not needed here.

2020-03-03 15:11 UTC, tochman commented on db/migrate/20200303132228_create_products.rb
> +      t.float :price
Should that really be a float? Not a blocker

2020-03-03 15:11 UTC, tochman commented on spec/factories/products.rb
> +    category_id { "" }
This one has to go

2020-03-03 15:11 UTC, tochman commented on spec/models/product_spec.rb
> +end
Please add a test for the factory

2020-03-03 15:11 UTC, tochman commented on spec/requests/api/products_spec.rb
> +end
Plz mind code formatting.

2020-03-03 15:11 UTC, tochman commented on spec/requests/api/products_spec.rb
> +    before do
Please consider this:

```ruby
let!(:products) { 3.times { FactoryBot.create(:product) } }
```

Then, you can test if the response has data about 3 products.

2020-03-04 08:07 UTC, emtalen commented on app/models/product.rb
> +  validates_presence_of :category_id, :name, :price
Its is removed

2020-03-04 17:44 UTC, tochman approved these changes

2020-03-04 17:44 UTC, merged